### ISSUE TITLE
Differences between Fedimint and Calckey!

### ISSUE THREAD

**Issue by ThatOneCalculator** [mint-lgbt/fedimint#1]
Hey! I just was wondering what the differences are, and if you'd be interested in maybe getting them merged upstream :)

**Comment by lunaisnotaboy** [comment]
Most of the pushed stuff is branding-related (e.g. icons and translations), as well as some missing types (I [got type definitions for `syslog-pro`](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61672) and [fixed a type in the logger](https://github.com/mint-lgbt/fedimint/commit/3561bcc9e6b4ea7ab8b88eb210af32efe6651b88)). Right now I'm currently going through the files and formatting and fixing types, linter errors, and a bunch of changes to where the components and stuff are. That's not pushed yet, as I'd like to wait until I finish it and test it out, as Fedimint runs on the `develop` branch.

If you'd like to accept the changes regarding formatting, types, and errors, I'd be happy to submit them!

**Comment by lunaisnotaboy** [comment]
[the-federation.info](https://the-federation.info) is already categorizing Fedimint as a Misskey instance, so I don't want to break things now. As for why I changed it, there are few things that I'd like to do down the line, but not yet as I'm trying to clean up the code right now.

I'll create the pull request once I've gone through everything, but it'll be a minute. Sorry.

**Comment by ThatOneCalculator** [comment]
TheFederation is actually kinda broken aorn with fetching new data, and I'm more so talking about https://calckey.fediverse.observer

**Comment by lunaisnotaboy** [comment]
I see. I'll change it to Calckey, but in the future I'll likely change it back once there are more changes. Sorry!

**Comment by lunaisnotaboy** [comment]
Closing this. I'll write a document that will keep track of the changes from Calckey in a few days.

**Comment by lunaisnotaboy** [comment]
Thank you for creating Calckey! Really, really like Rose Pine and everything you've done.
